name: List PRs and Tag Assignees

on:
  schedule:
    - cron: '50 4,13 * * *'  # Runs at 4 AM and 1 PM UTC (8 AM and 5 PM UTC+4)

jobs:
  list_and_tag_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: List Open PRs and Tag Assignees
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            const testResponse = await fetch(`https://api.github.com/user`, {
            headers: {
                Authorization: `token ${github.token}`,
                Accept: 'application/vnd.github.v3+json',
            },
            });
            const testData = await testResponse.json();
            console.log(testData); // Check if you get user data or an error

            echo "Fetching open PRs..."
            prs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/${{ github.repository }}/pulls?state=open")

            echo "Processing PRs..."
            one_minute_ago=$(date -u -d "1 minute ago" +"%Y-%m-%dT%H:%M:%SZ")

            for row in $(echo "${prs}" | jq -r '.[] | @base64'); do
                _jq() {
                echo ${row} | base64 --decode | jq -r ${1}
                }

                pr_number=$(_jq '.number')
                pr_title=$(_jq '.title')
                pr_updated_at=$(_jq '.updated_at')
                assignees=$(_jq '.assignees | map(.login) | join(", ")')

                if [[ "$pr_updated_at" < "$one_minute_ago" ]]; then
                if [ -n "$assignees" ]; then
                    echo "Tagging assignees for PR #${pr_number}: ${assignees}"
                    curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
                    -H "Content-Type: application/json" \
                    -d "{\"body\": \"@${assignees} Please review this PR.\"}" \
                    "https://api.github.com/repos/${{ github.repository }}/issues/${pr_number}/comments"
                else
                    echo "No assignees for PR #${pr_number}"
                fi
                else
                echo "PR #${pr_number} was updated within the last minute"
                fi
            done
